[package]
name = "rustyraft"
version = "0.1.0"
authors = ["Lucio Franco <lucio.franco@du.edu>"]

[dependencies]
futures = "*"
tokio-core = "0.1.3"
tokio-proto = "0.1.0"
bincode = "1.0.0-alpha2"
serde = "0.9"
serde_derive = "0.9"
byteorder = "1.0.0"